### ISSUE TITLE
Type error in package.json

### ISSUE THREAD

**Issue by skennic** [manuelmartin-developer/react-simtip#8]
Hello @manuelmartin-developer,

upon importing your package into my application I discovered that there is a typing error in the package.json file. To be exact, there is a comma in the path at line 22 `"main": ",/dist/index.cjs.js",`. Can you please correct it and provide an updated version on npm?

Kind Regards
Ken-Nic Schuster

**Comment by manuelmartin-developer** [comment]
Hi @skennic!

Thanks for your issue.
Last version should fix the problem --> [fix: Correct main entry path in package.json](https://github.com/manuelmartin-developer/react-simtip/commit/be25941f477e7872855978a573cc4b15715ccd01)

https://www.npmjs.com/package/react-simtip/v/2.1.1
